module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://robohatch.com',
  generateRobotsTxt: true,
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/admin',
          '/admin/*',
          '/api/',
          '/cart',
          '/checkout',
          '/login',
          '/register',
          '/forgot-password',
          '/profile',
          '/my-orders',
          '/orders/*',
          '/order/*',
          '/payment',
          '/cancelled-orders',
        ],
      },
    ],
  },
  exclude: [
    '/admin',
    '/admin/*',
    '/api/*',
    '/cart',
    '/checkout',
    '/login',
    '/register',
    '/forgot-password',
    '/profile',
    '/my-orders',
    '/orders/*',
    '/order/*',
    '/payment',
    '/cancelled-orders',
    '/login-example',
    '/protected-example',
    '/_app',
    '/_document',
  ],
  additionalPaths: async (config) => [
    await config.transform(config, '/'),
    await config.transform(config, '/about'),
    await config.transform(config, '/contact'),
    await config.transform(config, '/categories'),
    await config.transform(config, '/devotional'),
    await config.transform(config, '/jewelry'),
    await config.transform(config, '/homedecor'),
    await config.transform(config, '/toys'),
    await config.transform(config, '/office'),
    await config.transform(config, '/keychains'),
    await config.transform(config, '/lamps'),
    await config.transform(config, '/flowerpots'),
    await config.transform(config, '/phoneaccessories'),
    await config.transform(config, '/superhero-models'),
    await config.transform(config, '/idols'),
    await config.transform(config, '/custom-printing'),
    await config.transform(config, '/faqs'),
    await config.transform(config, '/terms-and-conditions'),
  ],
  transform: async (config, path) => {
    return {
      loc: path,
      changefreq: path === '/' ? 'daily' : 'weekly',
      priority: path === '/' ? 1.0 : 0.7,
      lastmod: new Date().toISOString(),
    }
  },
}
